AllCops:
  TargetRubyVersion: 3.4
inherit_from:
  - ~/.rubocop.yml
Style/StringLiterals:
  Enabled: true
Style/Documentation:
  Enabled: false
Style/CaseEquality:
  Enabled: false
Style/LambdaCall:
  Enabled: false
